language: java

dist: xenial

jdk: openjdk11

git:
  depth: false
  
addons: 
  sonarcloud:
    organization: "alessandroferi-github"
    
install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    
script:
  - mvn -f bookshop-project/pom.xml clean verify -Pjacoco
  - mvn -f bookshop-project/pom.xml sonar:sonar