language: java

dist: xenial

jdk: openjdk11

services: 
  - docker

git:
  depth: false
  
addons: 
  sonarcloud:
    organization: "alessandroferi-github"
    
# skip installation step
install: true

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache
    
script:
  - mvn -f bookshop-project/pom.xml clean verify -Pjacoco
  - mvn -f bookshop-project/pom.xml verify -Pjacoco,integration-tests
  - mvn -f bookshop-project/pom.xml coveralls:report sonar:sonar